SKILLS = ["Select skills...","ActionScript", "C", "C#", "C++", "Common Lisp",
  "CSS", "Diff", "Emacs Lisp", "Erlang", "Haskell", "HTML",
  "Java", "JavaScript", "Lua", "Objective-C", "Perl", "PHP",
  "Python", "Ruby", "Scala", "Scheme", "SQL", "TeX", "XML",
  "ABAP", "Ada", "ApacheConf", "Apex", "AppleScript", "Arc",
  "Arduino", "ASP", "Assembly", "Augeas", "AutoHotkey", "Awk",
  "Batchfile", "Befunge", "BlitzMax", "Boo", "Brainfuck",
  "Bro", "C-ObjDump", "C2hs Haskell", "Ceylon", "ChucK",
  "CLIPS", "Clojure", "CMake", "CoffeeScript", "ColdFusion",
  "Coq", "Cpp-ObjDump", "Cucumber", "Cython", "D", "D-ObjDump",
  "Darcs Patch", "Dart", "DCPU-16 ASM", "Delphi", "DOT",
  "Dylan", "eC", "Ecere Projects", "Ecl", "edn", "Eiffel",
  "Elixir", "Elm", "F#", "Factor", "Fancy", "Fantom", "fish",
  "Forth", "FORTRAN", "GAS", "Genshi", "Gentoo Ebuild",
  "Gentoo Eclass", "Gettext Catalog", "Go", "Gosu", "Groff",
  "Groovy", "Groovy Server Pages", "Haml", "Handlebars",
  "Haxe", "HTML+Django", "HTML+ERB", "HTML+PHP", "HTTP",
  "INI", "Io", "Ioke", "IRC log", "Java Server Pages", "JSON",
  "Julia", "Kotlin", "Lasso", "Less", "LilyPond",
  "Literate CoffeeScript", "Literate Haskell", "LiveScript",
  "LLVM", "Logos", "Logtalk", "Makefile", "Mako", "Markdown",
  "Matlab", "Max", "MiniD", "Mirah", "Monkey", "Moocode",
  "MoonScript", "mupad", "Myghty", "Nemerle", "Nginx",
  "Nimrod", "NSIS", "Nu", "NumPy", "ObjDump", "Objective-J",
  "OCaml", "Omgrofl", "ooc", "Opa", "OpenCL", "OpenEdge ABL",
  "Parrot", "Parrot Assembly", "Parrot Internal Representation",
  "Pike", "PogoScript", "PowerShell", "Prolog", "Puppet",
  "Pure Data", "Python traceback", "R", "Racket",
  "Ragel in Ruby Host", "Raw token data", "Rebol", "Redcode",
  "reStructuredText", "RHTML", "Rouge", "Rust", "Sage",
  "Sass", "Scilab", "SCSS", "Self", "Shell", "Smalltalk",
  "Smarty", "Standard ML", "SuperCollider", "Tcl", "Tcsh",
  "Tea", "Textile", "TOML", "Turing", "Twig", "TXL",
  "TypeScript", "Vala", "Verilog", "VHDL", "VimL",
  "Visual Basic", "XProc", "XQuery", "XS", "XSLT", "Xtend", "YAML"]
